-- WARNING: This file has been superseded and must NOT be applied.
--
-- It was originally created alongside 00002_rls_fixes.sql, giving two files
-- the same numeric prefix (00002_*). This causes Supabase CLI to apply them
-- in an undefined order, breaking the migration sequence.
--
-- The contents of this file have been split into the correct files:
--   • The RLS fixes (section 1) are already in  → 00002_rls_fixes.sql
--   • The yacht domain tables (sections 2–5) are now in → 00003_yacht_domain.sql
--
-- If you already applied this file in a dev environment, reset your local
-- Supabase instance before re-running migrations:
--   supabase db reset
